from pathlib import Path
import re


ROOT = Path(__file__).parent
OUT_FILE = ROOT / "kaggle_autodiff_single.py"

# Keep this order so dependencies are defined before use.
SOURCE_FILES = [
    "backend.py",
    "node.py",
    "module.py",
    "data.py",
    "test.py",
]

LOCAL_MODULES = {"backend", "node", "module", "data"}


def _strip_local_imports(code: str) -> str:
    lines = []
    skip_multiline = False
    paren_depth = 0

    for line in code.splitlines():
        if skip_multiline:
            paren_depth += line.count("(") - line.count(")")
            if paren_depth <= 0:
                skip_multiline = False
            continue

        from_match = re.match(r"^\s*from\s+([a-zA-Z_][\w]*)\s+import\b", line)
        if from_match and from_match.group(1) in LOCAL_MODULES:
            paren_depth = line.count("(") - line.count(")")
            if paren_depth > 0:
                skip_multiline = True
            continue

        if re.match(r"^\s*import\s+(backend|node|module|data)(\s|$)", line):
            continue

        lines.append(line)

    return "\n".join(lines).rstrip() + "\n"


def _fix_test_runtime_call(code: str) -> str:
    # Keep the generated one-file script runnable even if test.py was edited.
    return code.replace(
        "probs = model()",
        "probs = model(dataloader_train.xp.asarray(X_test))",
    )


def _append_gpu_smoke_test(code: str) -> str:
    block = """

print("\\n=== GPU Smoke Test ===")
print("GPU available:", gpu_available())

if gpu_available():
    dataloader_train.to_device("gpu")
    model.to_gpu()

    Xb, yb = next(iter(dataloader_train))
    probs_gpu = model(Xb)
    print("Batch output shape:", probs_gpu.shape)
    print("Batch output device:", probs_gpu.device)
    print("First logits row:", probs_gpu.value[0][:5])
else:
    print("CuPy not available in this environment; run this script on a GPU runtime.")
"""
    return code.rstrip() + "\n" + block


def build_single_file() -> Path:
    sections = [
        "# Auto-generated by build_kaggle_single_file.py",
        "# Consolidated single-file version for Kaggle testing.",
        "",
    ]

    for filename in SOURCE_FILES:
        path = ROOT / filename
        code = path.read_text(encoding="utf-8")
        code = _strip_local_imports(code)

        if filename == "test.py":
            code = _fix_test_runtime_call(code)

        sections.append(f"\n# ===== BEGIN {filename} =====\n")
        sections.append(code)
        sections.append(f"\n# ===== END {filename} =====\n")

    merged = "\n".join(sections)
    merged = _append_gpu_smoke_test(merged)

    OUT_FILE.write_text(merged, encoding="utf-8")
    return OUT_FILE


if __name__ == "__main__":
    out = build_single_file()
    print(f"Wrote consolidated script: {out}")
