# Auto-generated by build_kaggle_single_file.py
# Consolidated single-file version for Kaggle testing.


# ===== BEGIN backend.py =====

import numpy as np
from importlib import import_module

try:
    cp = import_module("cupy")
except ImportError:
    cp = None


def gpu_available() -> bool:
    return cp is not None


def ensure_device_available(device: str):
    if device == "gpu" and not gpu_available():
        raise RuntimeError("cupy is not available, cannot use GPU device")


def xp_for_device(device: str):
    ensure_device_available(device)
    return cp if device == "gpu" else np


def infer_device_from_value(value) -> str:
    module_name = type(value).__module__
    if module_name.startswith("cupy"):
        return "gpu"
    return "cpu"


def asarray_on_device(value, device: str):
    return xp_for_device(device).asarray(value)

class Backend:
    xp = np

    @staticmethod
    def use_gpu():
        ensure_device_available("gpu")
        Backend.xp = cp
    
    @staticmethod
    def use_cpu():
        Backend.xp = np

def xp():
    return Backend.xp


# ===== END backend.py =====


# ===== BEGIN node.py =====

from typing import Any, Callable, List, Literal, Optional, Union



Value = Union["Node", Any]


class NodeData:
    def __init__(
        self,
        value: Any,
        grad: Any = None,
        device: Literal["cpu", "gpu"] = "cpu",
    ):
        self._device: Literal["cpu", "gpu"] = "cpu"
        self._value: Any = None
        self._grad: Any = None
        self.device = device
        self.value = value

        if grad is None:
            self.grad = self.xp.zeros_like(self.value)
        else:
            self.grad = grad

    @property
    def xp(self):
        return xp_for_device(self._device)

    @property
    def device(self) -> Literal["cpu", "gpu"]:
        return self._device

    @device.setter
    def device(self, device: Literal["cpu", "gpu"]):
        ensure_device_available(device)
        self._device = device

    def _coerce(self, obj: Any, wrap_scalar: bool = True):
        xpl = self.xp
        if isinstance(obj, Node):
            obj = obj.value

        if wrap_scalar and xpl.isscalar(obj):
            return xpl.array([[obj]], dtype=xpl.float64)
        return xpl.asarray(obj)

    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, value: Any):
        self._value = self._coerce(value, wrap_scalar=True)

    @property
    def grad(self):
        return self._grad

    @grad.setter
    def grad(self, grad: Any):
        self._grad = self._coerce(grad, wrap_scalar=True)

    def to_device(self, device: Literal["cpu", "gpu"]):
        if device == self.device:
            return self

        self._value = asarray_on_device(self._value, device)
        self._grad = asarray_on_device(self._grad, device)
        self.device = device
        return self

    def __getattr__(self, name: str):
        return getattr(self._value, name)


class Node:
    def __init__(
        self,
        label: str,
        value: Any,
        grad: Any = None,
        children: Optional[List["Node"]] = None,
        _backward: Optional[Callable] = None,
        device: Literal["cpu", "gpu"] = "cpu",
    ):
        self.label = label

        if isinstance(value, NodeData):
            self.data = value
        else:
            self.data = NodeData(value=value, grad=grad, device=device)

        self.children = children if children is not None else []
        self._backward = _backward if _backward is not None else (lambda: None)

    @property
    def xp(self):
        return self.data.xp

    @property
    def value(self):
        return self.data.value

    @value.setter
    def value(self, v: Any):
        self.data.value = v

    @property
    def grad(self):
        return self.data.grad

    @grad.setter
    def grad(self, g: Any):
        self.data.grad = g

    @property
    def device(self) -> Literal["cpu", "gpu"]:
        return self.data.device

    def zero_grad(self):
        self.grad = self.xp.zeros_like(self.grad)

    def to_device(self, device: Literal["cpu", "gpu"]):
        self.data.to_device(device)
        return self

    def to_gpu(self):
        return self.to_device("gpu")

    def to_cpu(self):
        return self.to_device("cpu")

    @staticmethod
    def _infer_device(value: Any) -> Literal["cpu", "gpu"]:
        return infer_device_from_value(value)

    @staticmethod
    def zeros(shape: tuple, device: Literal["cpu", "gpu"] = "cpu"):
        xpl = xp_for_device(device)
        return Node("zeros", xpl.zeros(shape), device=device)

    @staticmethod
    def ones(shape: tuple, device: Literal["cpu", "gpu"] = "cpu"):
        xpl = xp_for_device(device)
        return Node("ones", xpl.ones(shape), device=device)

    @staticmethod
    def randn(shape, scale: float = 1.0, device: Literal["cpu", "gpu"] = "cpu"):
        xpl = xp_for_device(device)
        return Node("randn", xpl.random.randn(*shape) * scale, device=device)

    @staticmethod
    def __ensure_node(obj: Value, device: Optional[Literal["cpu", "gpu"]] = None) -> "Node":
        if isinstance(obj, Node):
            if device is not None and obj.device != device:
                raise RuntimeError(
                    f"Device mismatch: expected '{device}', got '{obj.device}'"
                )
            return obj

        inferred_device = device if device is not None else Node._infer_device(obj)
        return Node(str(obj), obj, device=inferred_device)

    @staticmethod
    def __align_devices(a: "Node", b: "Node") -> tuple["Node", "Node"]:
        if a.device == b.device:
            return a, b
        raise RuntimeError(
            f"Device mismatch: left operand on '{a.device}', right operand on '{b.device}'"
        )

    @staticmethod
    def __sum_to_shape(grad, shape: tuple, xpl):
        if grad.shape == shape:
            return grad

        lead = grad.ndim - len(shape)
        if lead < 0:
            raise ValueError(f"Cannot reduce grad shape {grad.shape} to target shape {shape}")

        if lead:
            grad = xpl.sum(grad, axis=tuple(range(lead)))

        if not shape:
            return xpl.array(grad.sum())

        reduce_axes = tuple(
            axis
            for axis, (gdim, tdim) in enumerate(zip(grad.shape, shape))
            if tdim == 1 and gdim != 1
        )
        if reduce_axes:
            grad = xpl.sum(grad, axis=reduce_axes, keepdims=True)

        return grad.reshape(shape)

    @staticmethod
    def relu(obj: Value) -> "Node":
        obj = Node.__ensure_node(obj)
        xpl = obj.xp
        value = xpl.maximum(0, obj.value)
        out = Node(f"relu({obj.label})", value, children=[obj], device=obj.device)

        def _backward():
            obj.grad += out.grad * (obj.value > 0)

        out._backward = _backward
        return out

    @staticmethod
    def sigmoid(obj: Value) -> "Node":
        obj = Node.__ensure_node(obj)
        xpl = obj.xp
        value = 1 / (1 + xpl.exp(-obj.value))
        out = Node(f"sigmoid({obj.label})", value, children=[obj], device=obj.device)

        def _backward():
            obj.grad += out.grad * value * (1 - value)

        out._backward = _backward
        return out

    @staticmethod
    def softmax(obj: Value) -> "Node":
        obj = Node.__ensure_node(obj)
        xpl = obj.xp
        shift = xpl.max(obj.value, keepdims=True, axis=1)
        exps = xpl.exp(obj.value - shift)
        probs = exps / xpl.sum(exps, keepdims=True, axis=1)
        out = Node(f"softmax({obj.label})", probs, children=[obj], device=obj.device)

        def _backward():
            v_dot_p = xpl.sum(out.grad * probs, axis=1, keepdims=True)
            obj.grad += probs * (out.grad - v_dot_p)

        out._backward = _backward
        return out

    @staticmethod
    def cross_entropy(probs: "Node", target_indices: Any) -> "Node":
        probs = Node.__ensure_node(probs)
        xpl = probs.xp
        batch_size = probs.value.shape[0]
        targets = xpl.asarray(target_indices)
        correct_confidences = probs.value[xpl.arange(batch_size), targets]
        loss_value = -xpl.mean(xpl.log(correct_confidences + 1e-15))

        out = Node(
            f"cross_entropy({probs.label})",
            xpl.array([[loss_value]]),
            children=[probs],
            device=probs.device,
        )

        def _backward():
            grad = xpl.zeros_like(probs.value)
            grad[xpl.arange(batch_size), targets] = -1.0 / (correct_confidences + 1e-15)
            probs.grad += (grad * out.grad) / batch_size

        out._backward = _backward
        return out

    @staticmethod
    def mse(values: "Node", target_values: Any) -> "Node":
        values = Node.__ensure_node(values)
        xpl = values.xp
        batch_size = values.value.shape[0]
        targets = xpl.asarray(target_values)
        diff = values.value[xpl.arange(batch_size)] - targets
        loss_value = xpl.mean(diff**2) / 2

        out = Node(
            f"mse({values.label})",
            xpl.array([[loss_value]]),
            children=[values],
            device=values.device,
        )

        def _backward():
            grad = values.value[xpl.arange(batch_size)] - targets
            values.grad += out.grad * grad

        out._backward = _backward
        return out

    @staticmethod
    def matmul(a: Value, b: Value) -> "Node":
        a = Node.__ensure_node(a)
        b = Node.__ensure_node(b)
        a, b = Node.__align_devices(a, b)

        value = a.value @ b.value
        out = Node(f"matmul({a.label}, {b.label})", value, children=[a, b], device=a.device)

        def _backward():
            a.grad += out.grad @ b.value.T
            b.grad += a.value.T @ out.grad

        out._backward = _backward
        return out

    @staticmethod
    def concat(a: Value, b: Value, axis: int = 1) -> "Node":
        a = Node.__ensure_node(a)
        b = Node.__ensure_node(b)
        a, b = Node.__align_devices(a, b)

        value = a.xp.concatenate((a.value, b.value), axis=axis)
        out = Node(f"concat({a.label}, {b.label})", value, children=[a, b], device=a.device)

        def _backward():
            split = a.value.shape[axis]

            if axis == 1:
                a.grad += out.grad[:, :split]
                b.grad += out.grad[:, split:]
            else:
                a.grad += out.grad[:split]
                b.grad += out.grad[split:]

        out._backward = _backward
        return out

    def sum(self) -> "Node":
        obj = Node.__ensure_node(self)
        xpl = obj.xp
        value = xpl.sum(obj.value)
        out = Node(f"sum({obj.label})", value=value, children=[obj], device=obj.device)

        def _backward():
            obj.grad += out.grad * xpl.ones_like(obj.value, dtype=xpl.float64)

        out._backward = _backward
        return out

    def abs(self) -> "Node":
        obj = Node.__ensure_node(self)
        xpl = obj.xp
        value = xpl.abs(obj.value)
        out = Node(f"abs({obj.label})", value=value, children=[obj], device=obj.device)

        def _backward():
            obj.grad += out.grad * xpl.sign(obj.value)

        out._backward = _backward
        return out

    def __len__(self):
        return len(self.value)

    def __add__(self, obj: Value) -> "Node":
        obj = Node.__ensure_node(obj, device=self.device)
        left, right = Node.__align_devices(self, obj)
        out = Node(
            f"({left.label}+{right.label})",
            left.value + right.value,
            children=[left, right],
            device=left.device,
        )

        def _backward():
            left.grad += Node.__sum_to_shape(out.grad, left.value.shape, left.xp)
            right.grad += Node.__sum_to_shape(out.grad, right.value.shape, right.xp)

        out._backward = _backward
        return out

    def __mul__(self, obj: Value) -> "Node":
        obj = Node.__ensure_node(obj, device=self.device)
        left, right = Node.__align_devices(self, obj)
        out = Node(
            f"({left.label}*{right.label})",
            left.value * right.value,
            children=[left, right],
            device=left.device,
        )

        def _backward():
            left_contrib = out.grad * right.value
            right_contrib = out.grad * left.value
            left.grad += Node.__sum_to_shape(left_contrib, left.value.shape, left.xp)
            right.grad += Node.__sum_to_shape(right_contrib, right.value.shape, right.xp)

        out._backward = _backward
        return out

    def __neg__(self) -> "Node":
        return self * Node("-1", -1, device=self.device)

    def __sub__(self, obj: Value) -> "Node":
        return self + (-Node.__ensure_node(obj, device=self.device))

    def __truediv__(self, obj: Value) -> "Node":
        obj = Node.__ensure_node(obj, device=self.device)
        return self * (obj**-1)

    def __pow__(self, power: float) -> "Node":
        out = Node(f"({self.label}^{power})", self.value**power, children=[self], device=self.device)

        def _backward():
            self.grad += out.grad * power * (self.value ** (power - 1))

        out._backward = _backward
        return out

    def __str__(self):
        return f"{self.label}={self.value}"

    def __hash__(self):
        return id(self)

    def __getattr__(self, name):
        if name == "shape":
            return self.value.shape
        return object.__getattribute__(self, name)

    def backward(self):
        topo = []
        visited = set()

        def build(node):
            if node in visited:
                return
            visited.add(node)
            for child in node.children:
                build(child)
            topo.append(node)

        build(self)
        self.grad = self.xp.ones_like(self.value)
        for node in reversed(topo):
            node._backward()


# ===== END node.py =====


# ===== BEGIN module.py =====

from typing import Dict, List, Literal

class Module:
    def __init__(self):
        self._parameters: Dict[Node] = {}
        self._modules: Dict["Module"] = {}
        self.device: Literal["cpu", "gpu"] = "cpu"

    def parameters(self) -> List[Node]:
        params = [p for p in self._parameters.values()]
        for m in self._modules.values():
            params.extend(m.parameters())
        return params

    def __setattr__(self, name, value):
        if isinstance(value, Node):
            self._parameters[name] = value
        elif isinstance(value, Module):
            self._modules[name] = value
        object.__setattr__(self, name, value)

    def add_parameter(self, name: str, param: Node):
        self._parameters[name] = param

    def add_module(self, name: str, module: "Module"):
        self._modules[name] = module

    def __call__(self, *args, **kwargs):
        return self.forward(*args, **kwargs)
    
    def to_gpu(self):
        for param in self.parameters():
            param.to_gpu()
        self.device = "gpu"
        return self

    def forward(self, _):
        raise NotImplementedError


class Linear(Module):
    def __init__(self, in_dim: int, out_dim: int, label: str = ""):
        super().__init__()

        self.W = Node.randn((in_dim + 1, out_dim), 0.1)
        self.W.label = f"{label}.W" if label else "W"

    def forward(self, x):
        X = Node.concat(x, Node.ones((len(x), 1), device=self.W.device))
        return Node.matmul(X, self.W)


# ===== END module.py =====


# ===== BEGIN data.py =====

from typing import Literal


class Dataset:
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


class DataLoader:
    def __init__(
        self,
        dataset,
        batch_size=32,
        shuffle=True,
        device: Literal["cpu", "gpu"] = "cpu",
    ):
        self.dataset = dataset
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.device = device

    @property
    def xp(self):
        return xp_for_device(self.device)

    def to_device(self, device: Literal["cpu", "gpu"]):
        ensure_device_available(device)
        self.device = device
        return self

    def __iter__(self):
        idx = np.arange(len(self.dataset))

        if self.shuffle:
            np.random.shuffle(idx)

        for i in range(0, len(idx), self.batch_size):
            batch = idx[i : i + self.batch_size]
            X = self.dataset.X[batch]
            y = self.dataset.y[batch]
            yield self.xp.asarray(X), self.xp.asarray(y)


# ===== END data.py =====


# ===== BEGIN test.py =====

from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np

np.random.seed(42)

digits = load_digits()

X = digits.data
y = digits.target

ss = StandardScaler()
X_scaled = ss.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

dataset_train = Dataset(X_train, y_train)
DEVICE = "gpu" if gpu_available() else "cpu"
dataloader_train = DataLoader(dataset_train, device=DEVICE)

class MLP(Module):
    def __init__(self, input_dim: int):
        super().__init__()

        self.fc1 = Linear(input_dim, 128)
        self.fc2 = Linear(128, 64)
        self.fc3 = Linear(64, 10)
    
    def forward(self, x: np.ndarray):
        x = self.fc1(x)
        x = Node.sigmoid(x)
        x = self.fc2(x)
        x = Node.sigmoid(x)
        x = self.fc3(x)
        return Node.softmax(x)

model = MLP(64)
if DEVICE == "gpu":
    model.to_gpu()

epochs = 100
batch_size = 32
lr = 0.5
lmbda = 0.001
for i in range(epochs):
    idx = np.random.permutation(len(X_train))
    X_shuf = X_train[idx]
    y_shuf = y_train[idx]

    tot_loss = 0
    m = 0
    for X, y in dataloader_train:
        probs = model(X)
        loss = Node.cross_entropy(probs, y)

        params = model.parameters()
        for param in params:
            param.zero_grad()

        # L1 reg
        reg = sum(
            (w.abs().sum() for w in params),
            start=Node("reg", 0.0, device=DEVICE),
        )

        cost = loss + reg * lmbda

        tot_loss += loss.value
        
        cost.backward()

        for param in params:
            param.value -= lr * param.grad

        m += 1
    
    if i % 10 == 0:
        print(f"#{i // 10} Loss:", np.round((tot_loss / m).squeeze(), 4))


probs = model(dataloader_train.xp.asarray(X_test))
correct = np.sum(probs.value.argmax(axis=1) == y_test)
total = len(probs)
print("Correct:", correct)
print("Total:", total)
print("Test Accuracy:", np.round(correct / total, 4) * 100)


# ===== END test.py =====


print("\n=== GPU Smoke Test ===")
print("GPU available:", gpu_available())

if gpu_available():
    dataloader_train.to_device("gpu")
    model.to_gpu()

    Xb, yb = next(iter(dataloader_train))
    probs_gpu = model(Xb)
    print("Batch output shape:", probs_gpu.shape)
    print("Batch output device:", probs_gpu.device)
    print("First logits row:", probs_gpu.value[0][:5])
else:
    print("CuPy not available in this environment; run this script on a GPU runtime.")
